// Enhanced Mock Data with complete User schema
import { User, UserSession, UserActivity } from "./types/user";

// Generate comprehensive mock users with all fields
export const enhancedMockUsers: User[] = [
  {
    id: "USR001",
    email: "john.doe@example.com",
    username: "johndoe_runner",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=John",
    gender: "male",
    age: 28,
    height: 180,
    height_unit: "cm",
    weight: 75,
    weight_unit: "kg",
    running_experience: "intermediate",
    pace_band: "5:00-5:30 min/km",
    preferred_genres: ["Electronic", "Hip-Hop", "Rock"],
    status: "active",
    created_at: "2024-01-15T10:00:00Z",
    last_login_at: "2024-11-19T10:30:00Z",
    onboarding_completed: true,
    total_runs: 45,
    total_distance_km: 312.5,
    total_duration_minutes: 1560,
    avg_pace: "5:15 min/km",
  },
  {
    id: "USR002",
    email: "jane.smith@example.com",
    username: "janesmith_fit",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jane",
    gender: "female",
    age: 32,
    height: 168,
    height_unit: "cm",
    weight: 62,
    weight_unit: "kg",
    running_experience: "advanced",
    pace_band: "4:30-5:00 min/km",
    preferred_genres: ["Electronic", "Jazz", "Ambient"],
    status: "active",
    created_at: "2024-01-20T14:30:00Z",
    last_login_at: "2024-11-19T09:15:00Z",
    onboarding_completed: true,
    total_runs: 89,
    total_distance_km: 623.0,
    total_duration_minutes: 3120,
    avg_pace: "4:45 min/km",
  },
  {
    id: "USR003",
    email: "mike.johnson@example.com",
    username: "mikej_running",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    gender: "male",
    age: 35,
    height: 175,
    height_unit: "cm",
    weight: 82,
    weight_unit: "kg",
    running_experience: "beginner",
    pace_band: "6:00-6:30 min/km",
    preferred_genres: ["Rock", "Classical"],
    status: "inactive",
    created_at: "2024-02-01T09:00:00Z",
    last_login_at: "2024-10-20T14:22:00Z",
    onboarding_completed: true,
    total_runs: 23,
    total_distance_km: 115.0,
    total_duration_minutes: 920,
    avg_pace: "6:15 min/km",
  },
  {
    id: "USR004",
    email: "emily.brown@example.com",
    username: "emilyb_runner",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    gender: "female",
    age: 26,
    height: 165,
    height_unit: "cm",
    weight: 58,
    weight_unit: "kg",
    running_experience: "intermediate",
    pace_band: "5:30-6:00 min/km",
    preferred_genres: ["Lo-fi", "Ambient", "Electronic"],
    status: "active",
    created_at: "2024-02-10T11:00:00Z",
    last_login_at: "2024-11-19T18:45:00Z",
    onboarding_completed: true,
    total_runs: 67,
    total_distance_km: 402.0,
    total_duration_minutes: 2010,
    avg_pace: "5:45 min/km",
  },
  {
    id: "USR005",
    email: "david.wilson@example.com",
    username: "davidw_marathon",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    gender: "male",
    age: 40,
    height: 183,
    height_unit: "cm",
    weight: 78,
    weight_unit: "kg",
    running_experience: "advanced",
    pace_band: "4:00-4:30 min/km",
    preferred_genres: ["Electronic", "Hip-Hop", "Rock"],
    status: "active",
    created_at: "2024-02-15T08:00:00Z",
    last_login_at: "2024-11-19T08:00:00Z",
    onboarding_completed: true,
    total_runs: 112,
    total_distance_km: 896.0,
    total_duration_minutes: 4480,
    avg_pace: "4:15 min/km",
  },
  {
    id: "USR006",
    email: "sarah.martinez@example.com",
    username: "sarahm_run",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    gender: "female",
    age: 29,
    height: 170,
    height_unit: "cm",
    weight: 64,
    weight_unit: "kg",
    running_experience: "beginner",
    pace_band: "6:30-7:00 min/km",
    preferred_genres: ["Jazz", "Classical", "Lo-fi"],
    status: "active",
    created_at: "2024-03-01T10:30:00Z",
    last_login_at: "2024-11-18T16:30:00Z",
    onboarding_completed: true,
    total_runs: 34,
    total_distance_km: 170.0,
    total_duration_minutes: 1020,
    avg_pace: "6:45 min/km",
  },
  {
    id: "USR007",
    email: "chris.taylor@example.com",
    username: "christ_jog",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Chris",
    gender: "other",
    age: 24,
    height: 178,
    height_unit: "cm",
    weight: 70,
    weight_unit: "kg",
    running_experience: "beginner",
    pace_band: "7:00-7:30 min/km",
    preferred_genres: ["Ambient", "Classical"],
    status: "inactive",
    created_at: "2024-03-10T13:00:00Z",
    last_login_at: "2024-09-15T11:20:00Z",
    onboarding_completed: false,
    total_runs: 8,
    total_distance_km: 40.0,
    total_duration_minutes: 280,
    avg_pace: "7:15 min/km",
  },
  {
    id: "USR008",
    email: "amanda.garcia@example.com",
    username: "amandag_ultrarunner",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Amanda",
    gender: "female",
    age: 34,
    height: 172,
    height_unit: "cm",
    weight: 60,
    weight_unit: "kg",
    running_experience: "advanced",
    pace_band: "4:00-4:30 min/km",
    preferred_genres: ["Electronic", "Rock", "Hip-Hop"],
    status: "active",
    created_at: "2024-03-20T15:00:00Z",
    last_login_at: "2024-11-19T11:00:00Z",
    onboarding_completed: true,
    total_runs: 156,
    total_distance_km: 1248.0,
    total_duration_minutes: 6240,
    avg_pace: "4:15 min/km",
  },
  {
    id: "USR009",
    email: "james.anderson@example.com",
    username: "jamesa_runner",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    gender: "male",
    age: 31,
    height: 185,
    height_unit: "cm",
    weight: 80,
    weight_unit: "kg",
    running_experience: "intermediate",
    pace_band: "5:00-5:30 min/km",
    preferred_genres: ["Hip-Hop", "Rock", "Electronic"],
    status: "active",
    created_at: "2024-04-01T09:00:00Z",
    last_login_at: "2024-11-18T20:15:00Z",
    onboarding_completed: true,
    total_runs: 91,
    total_distance_km: 546.0,
    total_duration_minutes: 2730,
    avg_pace: "5:15 min/km",
  },
  {
    id: "USR010",
    email: "lisa.thomas@example.com",
    username: "lisat_fitness",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    gender: "female",
    age: 27,
    height: 163,
    height_unit: "cm",
    weight: 56,
    weight_unit: "kg",
    running_experience: "intermediate",
    pace_band: "5:30-6:00 min/km",
    preferred_genres: ["Lo-fi", "Jazz", "Ambient"],
    status: "active",
    created_at: "2024-04-15T12:00:00Z",
    last_login_at: "2024-11-19T07:30:00Z",
    onboarding_completed: true,
    total_runs: 45,
    total_distance_km: 270.0,
    total_duration_minutes: 1350,
    avg_pace: "5:45 min/km",
  },
];

// Generate user sessions
export const mockUserSessions: UserSession[] = [
  {
    id: "SES001",
    user_id: "USR001",
    started_at: "2024-11-19T10:30:00Z",
    ended_at: "2024-11-19T11:00:00Z",
    duration_seconds: 1800,
    status: "completed",
    total_distance_meters: 5500,
    avg_pace_per_km: 327,
    avg_heart_rate: 155,
    max_heart_rate: 172,
    calories_burned: 420,
    steps_count: 7200,
  },
  {
    id: "SES002",
    user_id: "USR001",
    started_at: "2024-11-17T09:15:00Z",
    ended_at: "2024-11-17T10:00:00Z",
    duration_seconds: 2700,
    status: "completed",
    total_distance_meters: 8000,
    avg_pace_per_km: 337,
    avg_heart_rate: 158,
    max_heart_rate: 175,
    calories_burned: 600,
    steps_count: 10500,
  },
  {
    id: "SES003",
    user_id: "USR001",
    started_at: "2024-11-15T07:00:00Z",
    ended_at: "2024-11-15T07:35:00Z",
    duration_seconds: 2100,
    status: "completed",
    total_distance_meters: 6500,
    avg_pace_per_km: 323,
    avg_heart_rate: 152,
    max_heart_rate: 170,
    calories_burned: 490,
    steps_count: 8500,
  },
  {
    id: "SES004",
    user_id: "USR002",
    started_at: "2024-11-19T09:15:00Z",
    ended_at: "2024-11-19T10:00:00Z",
    duration_seconds: 2700,
    status: "completed",
    total_distance_meters: 10000,
    avg_pace_per_km: 270,
    avg_heart_rate: 165,
    max_heart_rate: 180,
    calories_burned: 650,
    steps_count: 13000,
  },
  {
    id: "SES005",
    user_id: "USR002",
    started_at: "2024-11-18T08:00:00Z",
    ended_at: "2024-11-18T09:00:00Z",
    duration_seconds: 3600,
    status: "completed",
    total_distance_meters: 12500,
    avg_pace_per_km: 288,
    avg_heart_rate: 162,
    max_heart_rate: 178,
    calories_burned: 780,
    steps_count: 16200,
  },
];

// Generate user activities
export const mockUserActivities: UserActivity[] = [
  {
    id: "ACT001",
    user_id: "USR001",
    event_type: "session_complete",
    event_data: { session_id: "SES001", distance_km: 5.5, duration_min: 30 },
    created_at: "2024-11-19T11:00:00Z",
  },
  {
    id: "ACT002",
    user_id: "USR001",
    event_type: "login",
    event_data: { ip_address: "192.168.1.1", device: "Android" },
    created_at: "2024-11-19T10:25:00Z",
  },
  {
    id: "ACT003",
    user_id: "USR001",
    event_type: "profile_update",
    event_data: {
      field: "preferred_genres",
      old_value: ["Electronic"],
      new_value: ["Electronic", "Hip-Hop", "Rock"],
    },
    created_at: "2024-11-18T15:30:00Z",
  },
  {
    id: "ACT004",
    user_id: "USR001",
    event_type: "session_complete",
    event_data: { session_id: "SES002", distance_km: 8.0, duration_min: 45 },
    created_at: "2024-11-17T10:00:00Z",
  },
  {
    id: "ACT005",
    user_id: "USR001",
    event_type: "session_start",
    event_data: { session_id: "SES002" },
    created_at: "2024-11-17T09:15:00Z",
  },
  {
    id: "ACT006",
    user_id: "USR002",
    event_type: "session_complete",
    event_data: { session_id: "SES004", distance_km: 10.0, duration_min: 45 },
    created_at: "2024-11-19T10:00:00Z",
  },
  {
    id: "ACT007",
    user_id: "USR002",
    event_type: "login",
    event_data: { ip_address: "192.168.1.5", device: "Android" },
    created_at: "2024-11-19T09:00:00Z",
  },
];

// Helper function to get user by ID
export const getUserById = (id: string): User | undefined => {
  return enhancedMockUsers.find((user) => user.id === id);
};

// Helper function to get sessions by user ID
export const getSessionsByUserId = (userId: string): UserSession[] => {
  return mockUserSessions.filter((session) => session.user_id === userId);
};

// Helper function to get activities by user ID
export const getActivitiesByUserId = (userId: string): UserActivity[] => {
  return mockUserActivities.filter((activity) => activity.user_id === userId);
};
