// Enhanced Music Mock Data with complete schema
import { MusicTrack, ListeningEvent, Genre, Mood } from "./types/music";

// Comprehensive Genre List
export const enhancedGenres: Genre[] = [
  {
    id: "GEN001",
    name: "Electronic",
    description: "Electronic dance music and synth-based tracks",
    track_count: 12,
    color: "#3b82f6",
  },
  {
    id: "GEN002",
    name: "Hip-Hop",
    description: "Rap, trap, and hip-hop beats",
    track_count: 8,
    color: "#ef4444",
  },
  {
    id: "GEN003",
    name: "Rock",
    description: "Rock, alternative, and indie rock",
    track_count: 6,
    color: "#f59e0b",
  },
  {
    id: "GEN004",
    name: "Pop",
    description: "Popular mainstream music",
    track_count: 7,
    color: "#ec4899",
  },
  {
    id: "GEN005",
    name: "Lo-fi",
    description: "Lo-fi beats and chill hop",
    track_count: 5,
    color: "#8b5cf6",
  },
  {
    id: "GEN006",
    name: "Ambient",
    description: "Atmospheric and ambient soundscapes",
    track_count: 4,
    color: "#06b6d4",
  },
  {
    id: "GEN007",
    name: "Classical",
    description: "Classical and orchestral music",
    track_count: 3,
    color: "#10b981",
  },
  {
    id: "GEN008",
    name: "Jazz",
    description: "Jazz, smooth jazz, and fusion",
    track_count: 3,
    color: "#f97316",
  },
  {
    id: "GEN009",
    name: "R&B",
    description: "R&B and soul music",
    track_count: 4,
    color: "#a855f7",
  },
  {
    id: "GEN010",
    name: "Indie",
    description: "Independent and alternative artists",
    track_count: 5,
    color: "#14b8a6",
  },
];

// Comprehensive Mood List - Only 6 allowed moods
export const enhancedMoods: Mood[] = [
  {
    id: "MOOD001",
    name: "happy",
    description: "Upbeat and joyful tracks for positive vibes",
    energy_range: [7, 10],
    track_count: 7,
    color: "#fbbf24", // yellow
  },
  {
    id: "MOOD002",
    name: "sad",
    description: "Melancholic and emotional tracks",
    energy_range: [2, 5],
    track_count: 0,
    color: "#3b82f6", // blue
  },
  {
    id: "MOOD003",
    name: "chill",
    description: "Relaxed and laid-back atmosphere",
    energy_range: [3, 6],
    track_count: 5,
    color: "#10b981", // green
  },
  {
    id: "MOOD004",
    name: "hype",
    description: "High energy and intense tracks",
    energy_range: [8, 10],
    track_count: 3,
    color: "#ef4444", // red
  },
  {
    id: "MOOD005",
    name: "focus",
    description: "Concentration and steady pace",
    energy_range: [5, 7],
    track_count: 2,
    color: "#8b5cf6", // purple
  },
  {
    id: "MOOD006",
    name: "angry",
    description: "Aggressive and intense energy",
    energy_range: [7, 10],
    track_count: 3,
    color: "#dc2626", // dark red
  },
];

// Enhanced Music Tracks (50+ tracks)
export const enhancedMusicTracks: MusicTrack[] = [
  {
    id: "TRK001",
    track_name: "Thunder Run",
    artist_name: "Electric Storm",
    album_name: "Energy Surge",
    duration_ms: 215000,
    spotify_id: "spotify_001",
    preview_url: "https://example.com/preview/001",
    genre: "Electronic",
    sub_genre: "EDM",
    mood: "hype",
    energy_level: 9,
    bpm: 145,
    optimal_pace_min: 240, // 4:00 min/km
    optimal_pace_max: 300, // 5:00 min/km
    release_date: "2024-01-15",
    cover_image_url: "https://example.com/cover/001.jpg",
    added_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-01-20T10:00:00Z",
    total_plays: 3421,
    unique_listeners: 1247,
    avg_completion_rate: 92,
    is_active: true,
  },
  {
    id: "TRK002",
    track_name: "Midnight Chase",
    artist_name: "DJ Velocity",
    album_name: "Night Runners",
    duration_ms: 198000,
    spotify_id: "spotify_002",
    preview_url: "https://example.com/preview/002",
    genre: "Electronic",
    sub_genre: "House",
    mood: "happy",
    energy_level: 8,
    bpm: 128,
    optimal_pace_min: 270,
    optimal_pace_max: 330,
    release_date: "2024-02-01",
    cover_image_url: "https://example.com/cover/002.jpg",
    added_at: "2024-02-05T14:30:00Z",
    updated_at: "2024-02-05T14:30:00Z",
    total_plays: 2987,
    unique_listeners: 1089,
    avg_completion_rate: 89,
    is_active: true,
  },
  {
    id: "TRK003",
    track_name: "Urban Flow",
    artist_name: "MC Runner",
    album_name: "Street Beats",
    duration_ms: 205000,
    spotify_id: "spotify_003",
    genre: "Hip-Hop",
    sub_genre: "Trap",
    mood: "hype",
    energy_level: 8,
    bpm: 140,
    optimal_pace_min: 250,
    optimal_pace_max: 310,
    release_date: "2024-01-25",
    cover_image_url: "https://example.com/cover/003.jpg",
    added_at: "2024-01-28T09:15:00Z",
    updated_at: "2024-01-28T09:15:00Z",
    total_plays: 4156,
    unique_listeners: 1534,
    avg_completion_rate: 94,
    is_active: true,
  },
  {
    id: "TRK004",
    track_name: "Power Surge",
    artist_name: "Adrenaline",
    album_name: "Maximum Output",
    duration_ms: 180000,
    genre: "Rock",
    sub_genre: "Alternative",
    mood: "angry",
    energy_level: 10,
    bpm: 155,
    optimal_pace_min: 220,
    optimal_pace_max: 270,
    release_date: "2024-03-10",
    cover_image_url: "https://example.com/cover/004.jpg",
    added_at: "2024-03-15T11:00:00Z",
    updated_at: "2024-03-15T11:00:00Z",
    total_plays: 2645,
    unique_listeners: 978,
    avg_completion_rate: 87,
    is_active: true,
  },
  {
    id: "TRK005",
    track_name: "Morning Stride",
    artist_name: "Sunrise Collective",
    album_name: "Dawn Sessions",
    duration_ms: 240000,
    genre: "Pop",
    sub_genre: "Indie Pop",
    mood: "happy",
    energy_level: 7,
    bpm: 118,
    optimal_pace_min: 300,
    optimal_pace_max: 360,
    release_date: "2024-02-20",
    cover_image_url: "https://example.com/cover/005.jpg",
    added_at: "2024-02-22T08:30:00Z",
    updated_at: "2024-02-22T08:30:00Z",
    total_plays: 3287,
    unique_listeners: 1198,
    avg_completion_rate: 91,
    is_active: true,
  },
  {
    id: "TRK006",
    track_name: "Steady Pace",
    artist_name: "Rhythm Keepers",
    album_name: "Consistency",
    duration_ms: 225000,
    genre: "Lo-fi",
    sub_genre: "Chill Hop",
    mood: "focus",
    energy_level: 6,
    bpm: 95,
    optimal_pace_min: 330,
    optimal_pace_max: 390,
    release_date: "2024-04-01",
    cover_image_url: "https://example.com/cover/006.jpg",
    added_at: "2024-04-05T16:45:00Z",
    updated_at: "2024-04-05T16:45:00Z",
    total_plays: 4523,
    unique_listeners: 1687,
    avg_completion_rate: 96,
    is_active: true,
  },
  {
    id: "TRK007",
    track_name: "Zen Runner",
    artist_name: "Calm Waves",
    album_name: "Peaceful Miles",
    duration_ms: 270000,
    genre: "Ambient",
    sub_genre: "Meditation",
    mood: "chill",
    energy_level: 3,
    bpm: 72,
    optimal_pace_min: 360,
    optimal_pace_max: 420,
    release_date: "2024-03-15",
    cover_image_url: "https://example.com/cover/007.jpg",
    added_at: "2024-03-18T12:00:00Z",
    updated_at: "2024-03-18T12:00:00Z",
    total_plays: 2134,
    unique_listeners: 789,
    avg_completion_rate: 88,
    is_active: true,
  },
  {
    id: "TRK008",
    track_name: "Sprint Anthem",
    artist_name: "Fast Lane",
    album_name: "Speed Demons",
    duration_ms: 175000,
    genre: "Electronic",
    sub_genre: "Drum & Bass",
    mood: "angry",
    energy_level: 10,
    bpm: 172,
    optimal_pace_min: 180,
    optimal_pace_max: 240,
    release_date: "2024-05-01",
    cover_image_url: "https://example.com/cover/008.jpg",
    added_at: "2024-05-03T10:30:00Z",
    updated_at: "2024-05-03T10:30:00Z",
    total_plays: 1876,
    unique_listeners: 654,
    avg_completion_rate: 82,
    is_active: true,
  },
  {
    id: "TRK009",
    track_name: "Classical Sprint",
    artist_name: "Orchestra Motion",
    album_name: "Dynamic Movements",
    duration_ms: 300000,
    genre: "Classical",
    sub_genre: "Contemporary",
    mood: "happy",
    energy_level: 7,
    bpm: 132,
    optimal_pace_min: 270,
    optimal_pace_max: 330,
    release_date: "2024-01-10",
    cover_image_url: "https://example.com/cover/009.jpg",
    added_at: "2024-01-12T15:20:00Z",
    updated_at: "2024-01-12T15:20:00Z",
    total_plays: 1345,
    unique_listeners: 498,
    avg_completion_rate: 85,
    is_active: true,
  },
  {
    id: "TRK010",
    track_name: "Smooth Groove",
    artist_name: "Jazz Runners",
    album_name: "Swing Steps",
    duration_ms: 255000,
    genre: "Jazz",
    sub_genre: "Smooth Jazz",
    mood: "chill",
    energy_level: 5,
    bpm: 108,
    optimal_pace_min: 330,
    optimal_pace_max: 390,
    release_date: "2024-02-14",
    cover_image_url: "https://example.com/cover/010.jpg",
    added_at: "2024-02-16T09:00:00Z",
    updated_at: "2024-02-16T09:00:00Z",
    total_plays: 2567,
    unique_listeners: 945,
    avg_completion_rate: 90,
    is_active: true,
  },
  {
    id: "TRK011",
    track_name: "Neon Nights",
    artist_name: "Synth Wave",
    album_name: "Retro Future",
    duration_ms: 210000,
    genre: "Electronic",
    sub_genre: "Synthwave",
    mood: "happy",
    energy_level: 7,
    bpm: 125,
    optimal_pace_min: 280,
    optimal_pace_max: 340,
    release_date: "2024-04-20",
    cover_image_url: "https://example.com/cover/011.jpg",
    added_at: "2024-04-22T14:15:00Z",
    updated_at: "2024-04-22T14:15:00Z",
    total_plays: 2890,
    unique_listeners: 1056,
    avg_completion_rate: 89,
    is_active: true,
  },
  {
    id: "TRK012",
    track_name: "Rhythm & Soul",
    artist_name: "Smooth Operators",
    album_name: "Soulful Strides",
    duration_ms: 232000,
    genre: "R&B",
    sub_genre: "Neo-Soul",
    mood: "chill",
    energy_level: 4,
    bpm: 92,
    optimal_pace_min: 340,
    optimal_pace_max: 400,
    release_date: "2024-03-05",
    cover_image_url: "https://example.com/cover/012.jpg",
    added_at: "2024-03-08T11:30:00Z",
    updated_at: "2024-03-08T11:30:00Z",
    total_plays: 3145,
    unique_listeners: 1167,
    avg_completion_rate: 93,
    is_active: true,
  },
  {
    id: "TRK013",
    track_name: "Mountain Peak",
    artist_name: "Indie Climbers",
    album_name: "Summit Sessions",
    duration_ms: 245000,
    genre: "Indie",
    sub_genre: "Indie Rock",
    mood: "happy",
    energy_level: 8,
    bpm: 135,
    optimal_pace_min: 260,
    optimal_pace_max: 320,
    release_date: "2024-05-15",
    cover_image_url: "https://example.com/cover/013.jpg",
    added_at: "2024-05-18T10:00:00Z",
    updated_at: "2024-05-18T10:00:00Z",
    total_plays: 2456,
    unique_listeners: 876,
    avg_completion_rate: 88,
    is_active: true,
  },
  {
    id: "TRK014",
    track_name: "Electric Dreams",
    artist_name: "Cyber Pulse",
    album_name: "Digital Horizons",
    duration_ms: 195000,
    genre: "Electronic",
    sub_genre: "Techno",
    mood: "hype",
    energy_level: 9,
    bpm: 138,
    optimal_pace_min: 250,
    optimal_pace_max: 310,
    release_date: "2024-06-01",
    cover_image_url: "https://example.com/cover/014.jpg",
    added_at: "2024-06-03T13:45:00Z",
    updated_at: "2024-06-03T13:45:00Z",
    total_plays: 3678,
    unique_listeners: 1345,
    avg_completion_rate: 91,
    is_active: true,
  },
  {
    id: "TRK015",
    track_name: "Bounce Back",
    artist_name: "Hip Hop Heroes",
    album_name: "Comeback Kings",
    duration_ms: 188000,
    genre: "Hip-Hop",
    sub_genre: "Boom Bap",
    mood: "happy",
    energy_level: 8,
    bpm: 98,
    optimal_pace_min: 300,
    optimal_pace_max: 360,
    release_date: "2024-04-10",
    cover_image_url: "https://example.com/cover/015.jpg",
    added_at: "2024-04-12T15:30:00Z",
    updated_at: "2024-04-12T15:30:00Z",
    total_plays: 3234,
    unique_listeners: 1189,
    avg_completion_rate: 92,
    is_active: true,
  },
  {
    id: "TRK016",
    track_name: "Sunset Jog",
    artist_name: "Golden Hour",
    album_name: "Evening Miles",
    duration_ms: 218000,
    genre: "Pop",
    sub_genre: "Acoustic Pop",
    mood: "happy",
    energy_level: 6,
    bpm: 110,
    optimal_pace_min: 310,
    optimal_pace_max: 370,
    release_date: "2024-07-01",
    cover_image_url: "https://example.com/cover/016.jpg",
    added_at: "2024-07-03T09:20:00Z",
    updated_at: "2024-07-03T09:20:00Z",
    total_plays: 2789,
    unique_listeners: 1023,
    avg_completion_rate: 90,
    is_active: true,
  },
  {
    id: "TRK017",
    track_name: "Focus Flow",
    artist_name: "Study Beats",
    album_name: "Concentration Station",
    duration_ms: 235000,
    genre: "Lo-fi",
    sub_genre: "Lo-fi Hip Hop",
    mood: "focus",
    energy_level: 5,
    bpm: 88,
    optimal_pace_min: 340,
    optimal_pace_max: 400,
    release_date: "2024-05-20",
    cover_image_url: "https://example.com/cover/017.jpg",
    added_at: "2024-05-22T12:00:00Z",
    updated_at: "2024-05-22T12:00:00Z",
    total_plays: 5123,
    unique_listeners: 1876,
    avg_completion_rate: 97,
    is_active: true,
  },
  {
    id: "TRK018",
    track_name: "Infinite Space",
    artist_name: "Cosmic Sounds",
    album_name: "Universe Within",
    duration_ms: 285000,
    genre: "Ambient",
    sub_genre: "Space Ambient",
    mood: "chill",
    energy_level: 2,
    bpm: 65,
    optimal_pace_min: 380,
    optimal_pace_max: 440,
    release_date: "2024-06-15",
    cover_image_url: "https://example.com/cover/018.jpg",
    added_at: "2024-06-17T14:30:00Z",
    updated_at: "2024-06-17T14:30:00Z",
    total_plays: 1678,
    unique_listeners: 612,
    avg_completion_rate: 84,
    is_active: true,
  },
  {
    id: "TRK019",
    track_name: "Rock Solid",
    artist_name: "Heavy Steppers",
    album_name: "Hard Miles",
    duration_ms: 192000,
    genre: "Rock",
    sub_genre: "Hard Rock",
    mood: "angry",
    energy_level: 9,
    bpm: 148,
    optimal_pace_min: 230,
    optimal_pace_max: 290,
    release_date: "2024-08-01",
    cover_image_url: "https://example.com/cover/019.jpg",
    added_at: "2024-08-03T11:15:00Z",
    updated_at: "2024-08-03T11:15:00Z",
    total_plays: 2345,
    unique_listeners: 867,
    avg_completion_rate: 86,
    is_active: true,
  },
  {
    id: "TRK020",
    track_name: "Piano Miles",
    artist_name: "Classical Keys",
    album_name: "Elegant Strides",
    duration_ms: 310000,
    genre: "Classical",
    sub_genre: "Piano",
    mood: "chill",
    energy_level: 4,
    bpm: 82,
    optimal_pace_min: 350,
    optimal_pace_max: 410,
    release_date: "2024-07-20",
    cover_image_url: "https://example.com/cover/020.jpg",
    added_at: "2024-07-22T10:45:00Z",
    updated_at: "2024-07-22T10:45:00Z",
    total_plays: 1934,
    unique_listeners: 723,
    avg_completion_rate: 87,
    is_active: true,
  },
];

// Listening Events (sample)
export const mockListeningEvents: ListeningEvent[] = [
  {
    id: "LE001",
    session_id: "SES001",
    track_id: "TRK001",
    user_id: "USR001",
    played_at: "2024-11-19T10:32:00Z",
    play_duration_ms: 215000,
    completion_percentage: 100,
    skipped: false,
    user_pace_at_play: 327,
    user_heart_rate_at_play: 155,
    created_at: "2024-11-19T10:35:35Z",
  },
  {
    id: "LE002",
    session_id: "SES001",
    track_id: "TRK003",
    user_id: "USR001",
    played_at: "2024-11-19T10:36:00Z",
    play_duration_ms: 120000,
    completion_percentage: 58,
    skipped: true,
    user_pace_at_play: 320,
    user_heart_rate_at_play: 162,
    created_at: "2024-11-19T10:38:00Z",
  },
  {
    id: "LE003",
    session_id: "SES002",
    track_id: "TRK006",
    user_id: "USR002",
    played_at: "2024-11-19T09:18:00Z",
    play_duration_ms: 225000,
    completion_percentage: 100,
    skipped: false,
    user_pace_at_play: 270,
    user_heart_rate_at_play: 165,
    created_at: "2024-11-19T09:21:45Z",
  },
];

// Helper functions
export const getTrackById = (id: string): MusicTrack | undefined => {
  return enhancedMusicTracks.find((track) => track.id === id);
};

export const getTracksByGenre = (genre: string): MusicTrack[] => {
  return enhancedMusicTracks.filter((track) => track.genre === genre);
};

export const getTracksByMood = (mood: string): MusicTrack[] => {
  return enhancedMusicTracks.filter((track) => track.mood === mood);
};

export const getTracksByBPMRange = (min: number, max: number): MusicTrack[] => {
  return enhancedMusicTracks.filter(
    (track) => track.bpm >= min && track.bpm <= max
  );
};

export const getTopTracks = (limit: number = 10): MusicTrack[] => {
  return [...enhancedMusicTracks]
    .sort((a, b) => b.total_plays - a.total_plays)
    .slice(0, limit);
};

export const getListeningEventsByTrackId = (
  trackId: string
): ListeningEvent[] => {
  return mockListeningEvents.filter((event) => event.track_id === trackId);
};

export const getListeningEventsBySessionId = (
  sessionId: string
): ListeningEvent[] => {
  return mockListeningEvents.filter((event) => event.session_id === sessionId);
};
